<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="50.4250" tests="2" failures="1">
  <testsuite name="Root Suite" timestamp="2022-01-13T16:23:06" tests="0" file="cypress/integration/End2EndTest.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test Case - Synonyms" timestamp="2022-01-13T16:23:06" tests="2" time="50.1850" failures="1">
    <testcase name="Test Case - Synonyms Test Case: Synonym Anlegen" time="36.5120" classname="Test Case: Synonym Anlegen">
    </testcase>
    <testcase name="Test Case - Synonyms Test Case: Synonym Anlegen" time="0.0000" classname="Test Case: Synonym Anlegen">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;td.text-start&gt;&apos; to have text &apos;testExample1440&apos;, but the text was &apos;&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<td.text-start>' to have text 'testExample1440', but the text was ''
    at Context.eval (http://localhost/__cypress/tests?p=cypress/integration/End2EndTest.spec.js:9902:26)]]></failure>
    </testcase>
  </testsuite>
</testsuites>